### PR TITLE
Add tslint config for typescript projects

### PR DESCRIPTION
**Pull request by Dikaeinstein**
#### What does this PR do?
Add tslint config for typescript projects
#### Description of Task to be completed?
- add typescript, tslint and tslint-react
- add tests for tslint script
- add tslint default config
The lint script now checks if the project uses typescript then lint files using tslint and eslint
#### How should this be manually tested?
Run ```src/index.js lint``` or ```src/index.js tslint``` to use the tslint script directly
#### Issue
https://github.com/tricinel/frontwerk/issues/2

### CODE REVIEW

**Comment by iahtsy** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :exclamation: Big PR! If your PR contains multiple changes, splitting each into a separate PR will help faster, easier review.
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  You've made changes to one or more library files and you have not added any tests. That's OK as long as you're refactoring existing code.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by tricinel** [comment]
Wowza 🎉 ! Thank you so much @Dikaeinstein! I will take a proper look at this ASAP. It looks sweet on the first glance 👍 

I'm integrating TypeScript into a React project as I write this and what you're proposing is spot on. There's a few rules that are a matter of preference (for example single quotes in .ts but double in .tsx) and some tools that need to go with TypeScript (tslint-config-prettier to make it work with prettier like eslint and ts-jest so that we can write even tests in .ts). Overall, this is spot on!

Like I said, I will take a look at all this :)

I am also looking into integrating something like all-contributors (https://www.npmjs.com/package/all-contributors) into this. I'll open up a separate issue as soon as I have a bit of time on my hands.

**Comment by Dikaeinstein** [comment]
Thanks @tricinel for the feedback

**Comment by tricinel** [comment]
Hi @Dikaeinstein! I've merged this into develop for the time being and I will add some customizations to the rules and presets (e.g. adding prettier) if that's alright.

Thank you for contributing!

**Pull request merged**
